=== rumentoshev/MuseumCatalogue_XMLProject/DTD/catalog.dtd
<!ELEMENT catalog (regions, m_types, locations)>

<!ELEMENT regions (region+)>
<!ELEMENT region EMPTY>
<!ATTLIST region
        id ID #REQUIRED
        name CDATA #REQUIRED>

<!ELEMENT m_types (m_type+)>
<!ELEMENT m_type EMPTY>
<!ATTLIST m_type 
        id ID #REQUIRED
        type CDATA #REQUIRED>

<!ELEMENT locations (location+)>
<!ELEMENT location (museum_type+)>
<!ATTLIST location region_id IDREF #REQUIRED>

<!ELEMENT museum_type (museum+)>
<!ATTLIST museum_type m_type_id IDREF #REQUIRED>
<!ELEMENT museum (name, image, description, address, 
                  contacts, prices, working_hours)>

<!ELEMENT name (#PCDATA)>

<!ELEMENT image EMPTY>
<!ATTLIST image href ENTITY #REQUIRED>
<!NOTATION jpeg PUBLIC "image/jpeg">

<!ELEMENT description (#PCDATA)>
<!ELEMENT address (#PCDATA)> <!-- PITAI ZA ELEMENTI-->
<!ELEMENT contacts (phone+, email?)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT prices (entry_fee, lection)>
<!ELEMENT entry_fee (retiree, adults, children, students, disabled, groups)>
<!ELEMENT retiree (#PCDATA)>
<!ELEMENT adults (#PCDATA)>
<!ELEMENT children (#PCDATA)>
<!ELEMENT students (#PCDATA)>
<!ELEMENT disabled (#PCDATA)>
<!ELEMENT groups (#PCDATA)>
<!ELEMENT lection (language+)>
<!ELEMENT language (#PCDATA)>

<!ELEMENT working_hours (working_days, non-working_days)>
<!ELEMENT working_days (#PCDATA)>
<!ELEMENT non-working_days (#PCDATA)>

=== rumentoshev/MuseumCatalogue_XMLProject/XML/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="catalogXSL.xsl"?>
<!DOCTYPE catalog SYSTEM 'catalog.dtd' [
    <!ENTITY NHM SYSTEM "https://stolica.bg/wp-content/uploads/2019/03/nim_natsionalen_istoricheski_muzey_(6).JPG" NDATA jpeg>
    <!ENTITY NWIM SYSTEM "https://www.museology.bg/UserFiles/pictures/453F9A33-F0DD-8865-D46D-861D44E9513C.jpg?cache&w=1200" NDATA jpeg>
    <!ENTITY PrirNauc SYSTEM "https://upload.wikimedia.org/wikipedia/commons/7/78/Natural-history-sofia-ifb.JPG" NDATA jpeg>
    <!ENTITY Vraca SYSTEM "https://cdst.ro/wp-content/uploads/2019/07/IMG_6679.jpg" NDATA jpeg>
    <!ENTITY Osam SYSTEM "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Nsmus.jpg/220px-Nsmus.jpg" NDATA jpeg>
    <!ENTITY Preslav SYSTEM "https://upload.wikimedia.org/wikipedia/commons/9/9e/Preslav2.jpg" NDATA jpeg>
    <!ENTITY Etur SYSTEM "https://static.tildacdn.com/tild6438-3932-4838-b866-343530623565/Index-1640.jpg" NDATA jpeg>
]>


<catalog>
    <regions>
        <region id="NW" name="Northwest" />
        <region id="NC" name="North Central" />
        <region id="NE" name="Northeast" />
        <region id="SW" name="Southwest" />
        <region id="SC" name="South Central" />
        <region id="SE" name="Southeast" />
    </regions>
    <m_types>
        <m_type id="National" type="National Museum" />
        <m_type id="Regional_Historical" type="Regional Historical Museum" />
        <m_type id="Natural_History" type="Natural History Museum" />
        <m_type id="Archaeological" type="Archaeological Museum" />
        <m_type id="Etnographic" type="Etnographic Museum" />
    </m_types>
    <locations>
        <location region_id="SW">
            <museum_type m_type_id="National">
                <!-- NIM-->
                <museum>
                    <name>Национален исторически музей</name>
                    <image href="NHM" />
                    <description>Националния исторически музей е създаден с разпореждане на Бюрото
                        на Министерския съвет на НРБ през 1973 г. Първата експозиция е открита през
                        1984 г. в сградата на Съдебната палата в София в чест на 1300-годишнината от
                        създаването на българската държава.</description>
                    <address>Национален исторически музей, ул. „Витошко лале“ 16 ,София 1618
                        ,БЪЛГАРИЯ</address>
                    <contacts>
                        <phone>+359-(0)896 720 336 – за заявки</phone>
                        <phone>+359-(0)2-955 42 90 – директорски кабинет</phone>
                        <phone>+359-(0)2-955 76 04 – тел. централа</phone>
                        <email>nim.pr@historymuseum.org</email>
                    </contacts>
                    <prices>
                        <entry_fee>
                            <retiree>5.00 лв.</retiree>
                            <adults>5.00 лв.</adults>
                            <children>3.00 лв.</children>
                            <students>3.00 лв.</students>
                            <disabled>Безплатно</disabled>
                            <groups>10.00 лв.</groups>
                        </entry_fee>
                        <lection>
                            <language>български език – 20.00 лв.</language>
                            <language>чужд език – 35.00 лв.</language>
                            <language>български език с превод – 25.00 лв.</language>
                        </lection>
                    </prices>
                    <working_hours>
                        <working_days>понеделник – неделя (зимно 01.10 -31.03), 09:30 –18:00 ч.
                            (каса до 17:15 ч.) (лятно 01.04 – 30.09), 09:30 –19:00 ч. (каса до 18:15
                            ч.) </working_days>
                        <non-working_days>Няма почивни дни</non-working_days>
                    </working_hours>
                </museum>
                <!-- NWIM-->
                <museum>
                    <name>Национален военноисторически музей</name>
                    <image href="NWIM" />
                    <description>Националният военноисторически музей (НВИМ) е държавен музей, който
                        от създаването си до днес е структура на Министерство на отбраната
                        (респективно Министерство на войната и Министерство на народната отбрана).
                        Той издирва, съхранява, научно обработва и популяризира културни ценности,
                        свързани с националната и европейска военна история. НВИМ развива своята
                        дейност на територията на цялата страна. За своето вековно присъствие в
                        културноисторическото пространство в неговите фондове са съхранени и
                        проучени повече от 1 000 000 културни ценности, свидетели на българската и
                        европейска военна история.</description>
                    <address>България, 1505, гр. София, ул. „Черковна“ No 92</address>
                    <contacts>
                        <phone>+359 2/946 1805</phone>
                        <email>nvim@militarymuseum.bg</email>
                    </contacts>
                    <prices>
                        <entry_fee>
                            <retiree>2 лв.</retiree>
                            <adults>10 лв.</adults>
                            <children>(до 7 год.) безплатно</children>
                            <students>2 лв.</students>
                            <disabled>2 лв.</disabled>
                            <groups>От 12 до 20 души 2 лв. по- малко от редовната цена</groups>
                        </entry_fee>
                        <lection>
                            <language>Български език - 30/60 лв</language>
                            <language>Английски език - 30/60 лв</language>
                            <language>Немски език - 30/60 лв</language>
                            <language>Руски език - 30/60 лв</language>
                            <language>Френски език - 30/60 лв</language>
                        </lection>
                    </prices>
                    <working_hours>
                        <working_days>Сряда – Неделя 10 - 18 ч. </working_days>
                        <non-working_days>24.12 до 27.12 и 30.12 до 2.01</non-working_days>
                    </working_hours>
                </museum>
                <!-- PrirNauc-->
                <museum>
                    <name>Национален природонаучен музей</name>
                    <image href="PrirNauc" />
                    <description>Националният природонаучен музей е институция, посветена на запазването, изучаването и представянето на природното богатство и биоразнообразие на дадена страна или регион. Този тип музей обикновено играе ключова роля в образователната и научната общност, като насърчава интереса и разбирането за природата, екосистемите и животните.</description>
                    <address>бул. Цар Освободител 1, 1000 София</address>
                    <contacts>
                        <phone>087 9226573 – деловодство</phone>
                        <phone>087 7089048 – музеен магазин</phone>
                        <email>contact@nmnhs.com</email>
                    </contacts>
                    <prices>
                        <entry_fee>
                            <retiree>пенсионери и лица над 65 г. – 5 лв.</retiree>
                            <adults>Цена за възрастен – 10.00 лв.</adults>
                            <children>безплатно</children>
                            <students>Цена за деца от 3- 6 г. – 4.00 лв.</students>
                            <disabled>безплатно</disabled>
                            <groups>За групи от 10 и повече посетители – 4.00 лв.</groups>
                        </entry_fee>
                        <lection>
                            <language>Български език - 20 лв</language>
                            <language>Английски език - 30 лв</language>
                        </lection>
                    </prices>
                    <working_hours>
                        <working_days>за научните отдели: понеделник — петък от 08:30 до 17:00
                            за експозицията: понеделник — неделя 10:00 — 18:00 (последните посетители се допускат в 17:30 ч.)
                            на 24 и 31 декември от 10:00 до 13:00 ч.</working_days>
                        <non-working_days>1 януари, 3 март, Великден [православен] и 25 декември.</non-working_days>
                    </working_hours>
                </museum>
            </museum_type>
        </location>
        <location region_id="NW">
            <museum_type m_type_id="Regional_Historical">
                <!-- Vraca-->
                <museum>
                    <name>Регионален исторически музей - Враца</name>
                    <image href="Vraca" />
                    <description>Регионалният историческия музей- Враца е една от най- авторитетните
                        културни и научни институции в Северозападна България, в чиито фондове и
                        зали са съхранени над 120 000 движими културни ценности от всички
                        исторически епохи. В структурата на РИМ- Враца са включени: централна
                        сграда, лапидариум, етнографско- възрожденски комплекс „Св. Софроний
                        Врачански”, етнографско- възрожденски комплекс „Никола Войводов”,
                        средновековни жилищно- отбранителни кули- „Кула на Куртпашови” и „Кула на
                        мешчиите”. В експозиционните зали посетителите могат да се запознаят с
                        артефакти от световна величина като: уникалният глинен олтар с еленови рога
                        и раннонеолитните погребения „in situ”от с. Оходен, най- ранната
                        протописменост в света, тракийското съкровище(165 сребърни и сребърни с
